### PR TITLE
Refactored roles

### PR DESCRIPTION
**Pull request by tikhomirovd**
Have refactored roles for dataset. Added some new typings. Added decorator for inhering docs

### CODE REVIEW

**Comment by tikhomirovd** [comment]
Hi. There is some misunderstanding ways, i took them into todo
Added refactored of pandas_backend
1. in __init__ might be better to create empty dataset instead of None 
2. in. _get_column_index couldn't understand should return one column index or several. Rewrite this function as i see where always return int. Check it please

**Comment by tikhomirovd** [comment]
3. Check the tutorials if everything work, found the "problem". When we add column via roles, the dtype by default is None. Maybe should set dtype of object by default?

**Comment by tikhomirovd** [comment]
Screenshot 2024-04-27 at 12 33 01 PM

**Comment by tikhomirovd** [comment]
4. Also please check dypes cause a lot of warnings in pandas. Tried to debug and saw difference types in data, that's not ok

**Comment by VasilievaKA** [comment]
> Hi. There is some misunderstanding ways, i took them into todo Added refactored of pandas_backend
> 
> 1. in **init** might be better to create empty dataset instead of None
> 2. in. _get_column_index couldn't understand should return one column index or several. Rewrite this function as i see where always return int. Check it please

**Comment by VasilievaKA** [comment]
> 3. Check the tutorials if everything work, found the "problem". When we add column via roles, the dtype by default is None. Maybe should set dtype of object by default?

updated in new virsin of dataset after your pull

**Pull request closed without merging**
