### PR TITLE
Feature/experiments

### PR DESCRIPTION
**Pull request by Dmatryus**
An example has been added to predict the effect of the model.

### CODE REVIEW

**Review by VasilievaKA — DISMISSED** [review]
Good example!

**Comment by tikhomirovd** [comment]
All is good, but I think that we could add mde and sample size before A\B test to get full experiments.

**Comment by tikhomirovd** [comment]
#52

**Comment by tikhomirovd** [comment]
## 🚀 Feature Proposal

I propose adding a new Jupyter notebook example to the HypEx documentation and example section. This notebook would demonstrate how to predict the financial effect from a model, providing a practical guide for users to understand the impact of their models on financial metrics.

### Motivation

Our users often need to quantify the financial impact of their models to justify the implementation and further investment into model development. Providing a clear, step-by-step example of predicting model effects can significantly enhance user understanding and application of HypEx in real-world scenarios.

### Feature Description

The new notebook will include:

- An introduction to the concept of model effect prediction in the context of financial metrics.
- A step-by-step guide on creating a synthetic dataset with a known effect size.
- Instructions on fitting and estimating a random model using HypEx.
- Demonstrations of preprocessing data and conducting AA and AB tests to validate the predicted effects.
- Code snippets, explanations, and visualizations to aid understanding.

This example will utilize the `AATest` and `ABTest` classes from HypEx, showcasing their application in a practical experiment. The dataset creation process, model fitting, prediction, and testing phases will be covered comprehensively.

### Potential Impacts

This addition is expected to:

- Enhance the documentation and examples provided with HypEx, making the library more accessible to new users.
- Serve as an educational tool for understanding the application of HypEx in financial effect prediction.
- Encourage the adoption of HypEx by demonstrating its practical utility in model effect quantification.

### Alternatives

While users can independently research and implement model effect prediction, having a dedicated example within HypEx significantly lowers the barrier to entry and ensures consistent application of best practices.

### Additional Context

The proposed example will address common challenges and questions related to model effect prediction, providing a valuable resource for both new and experienced users of HypEx.

**Comment by tikhomirovd** [comment]
Please add this tutorial to the docs.

**Review by tikhomirovd — APPROVED** [review]
Great job

**Pull request merged**
